media:
  input: public/images
  output: images
  categories: [ "image" ]
content:
  - name: sites
    label: Sites
    type: collection
    path: public/_sites
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: url, label: Link, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: tags, label: Tags, type: string, list: true}
      
      