media:
  input: public/pictures
  output: /pictures
  categories: [ "image" ]
content:
  - name: sites
    label: Sites
    type: collection
    path: _sites
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: url, label: Link, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: tags, label: Tags, type: string, list: true}
      - { name: author, label: Author, type: string}
      