// These styles apply to every route in the application
import '../CSS/styles.css'
 
import {NextUIProvider} from "@nextui-org/react";
import * as React from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <NextUIProvider>
    
      <body>{children}</body>
      </NextUIProvider>
    </html>
  )
}